using System.Globalization;
using System.Resources;

namespace Roivo.Resources;

/// <summary>
/// Strongly-typed access to the validation <c>.resx</c> pair.
/// </summary>
/// <remarks>
/// Written by hand rather than generated by the designer: the generator relies
/// on a Visual Studio build step and is unreliable under plain
/// <c>dotnet build</c>, which is what CI and the container image use.
///
/// Why <c>.resx</c> here at all, when the other ~473 strings use
/// <see cref="Strings"/>? Because DataAnnotations resolves
/// <c>ErrorMessageResourceName</c> by reflecting for a public static property
/// on <c>ErrorMessageResourceType</c>, and an attribute argument must be a
/// compile-time constant — so a culture-switching property cannot be passed
/// directly to <c>[Required(ErrorMessage = …)]</c>. Naming the type and the key
/// is the only route that keeps validation messages translatable.
///
/// Each property reads through <see cref="ResourceManager"/> at call time, so
/// the message follows <see cref="CultureInfo.CurrentUICulture"/> for the
/// request — the same culture the localization middleware set.
/// </remarks>
public static class ValidationMessages
{
    private static readonly ResourceManager Manager =
        new("Roivo.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);

    /// <summary>The underlying manager. Exposed for tests and diagnostics.</summary>
    public static ResourceManager ResourceManager => Manager;

    private static string Get(string key)
        => Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    public static string AccountTypeRequired => Get(nameof(AccountTypeRequired));
    public static string ConfirmPasswordRequired => Get(nameof(ConfirmPasswordRequired));
    public static string OrganisationNameRequired => Get(nameof(OrganisationNameRequired));
    public static string EmailInvalid => Get(nameof(EmailInvalid));
    public static string AfmRequired => Get(nameof(AfmRequired));
    public static string AfmLength => Get(nameof(AfmLength));
    public static string PasswordRequired => Get(nameof(PasswordRequired));
    public static string PasswordsDoNotMatch => Get(nameof(PasswordsDoNotMatch));
    public static string TermsMustBeAccepted => Get(nameof(TermsMustBeAccepted));
    public static string EmailRequired => Get(nameof(EmailRequired));
    public static string FullNameRequired => Get(nameof(FullNameRequired));
    public static string FullNameTooShort => Get(nameof(FullNameTooShort));
}
